# Generated by Django 4.2.4 on 2023-08-27 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('document', models.CharField(max_length=15, verbose_name='Documento')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprovada automaticamente?')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='Analisada automaticamente em')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidade')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('status', models.SmallIntegerField(choices=[(1, 'Aprovado'), (2, 'Negado')], default=2, verbose_name='Status')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda mensal')),
                ('marital_status', models.SmallIntegerField(choices=[(1, 'Solteiro'), (2, 'Casado'), (3, 'Divorciado'), (4, 'Viúvo')], default=1, verbose_name='Estado civil')),
            ],
            options={
                'verbose_name': 'Análise de cliente',
                'verbose_name_plural': 'Análise de clientes',
            },
        ),
        migrations.CreateModel(
            name='UserFormConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_settings', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loans_for_good.customeranalysis')),
            ],
        ),
    ]
