# Generated by Django 4.2.4 on 2023-08-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_for_good', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeranalysis',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
    ]
