# Generated by Django 4.2.4 on 2023-08-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_for_good', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userformconfiguration',
            name='user',
        ),
        migrations.AlterField(
            model_name='customeranalysis',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Análisada automaticamente em'),
        ),
    ]
