# Generated by Django 4.2.4 on 2023-08-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans_for_good', '0002_alter_customeranalysis_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeranalysis',
            old_name='aprroved',
            new_name='approved',
        ),
    ]
