# Generated by Django 4.2.4 on 2023-08-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_for_good', '0003_alter_userformconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userformconfiguration',
            name='field_settings',
            field=models.JSONField(default=dict),
        ),
    ]
