# Generated by Django 4.2.4 on 2023-08-26 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans_for_good', '0003_rename_aprroved_customeranalysis_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFormConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_settings', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loans_for_good.customeranalysis')),
            ],
        ),
    ]
