# Generated by Django 4.2.4 on 2023-08-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_for_good', '0004_alter_userformconfiguration_field_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userformconfiguration',
            name='name',
            field=models.CharField(default=None, max_length=200, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
