# Generated by Django 4.2.4 on 2023-08-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_for_good', '0004_userformconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeranalysis',
            name='analyzed_at',
            field=models.DateTimeField(default=None, verbose_name='Analisada em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeranalysis',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Aprovado'), (2, 'Negado')], default=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='customeranalysis',
            name='marital_status',
            field=models.SmallIntegerField(choices=[(1, 'Solteiro'), (2, 'Casado'), (3, 'Divorciado'), (4, 'Viúvo')], default=1, verbose_name='Estado civil'),
        ),
    ]
