# Generated by Django 4.2.4 on 2023-08-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_for_good', '0005_customeranalysis_analyzed_at_customeranalysis_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeranalysis',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Analisada em'),
        ),
    ]
