version: '3'
services:
  web:
    container_name: "django"
    image: python:latest
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=loans_for_good.settings
    depends_on:
      - db
    tty: true
    stdin_open: true
    networks:
      - digitalsys_network
  
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=digitalsys
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    networks:
      - digitalsys_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - digitalsys_network

  celery:
    build: .
    container_name: celery
    command: celery -A celery_tasks worker -Q default -l info -Ofair -E
    volumes:
      - ./:/home/app
    networks:
      - digitalsys_network
    depends_on:
      - db
      - redis

networks:
  digitalsys_network:
